/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Public } from "../../decorators/public.decorator";
import { CreateAnswerArgs } from "./CreateAnswerArgs";
import { UpdateAnswerArgs } from "./UpdateAnswerArgs";
import { DeleteAnswerArgs } from "./DeleteAnswerArgs";
import { AnswerCountArgs } from "./AnswerCountArgs";
import { AnswerFindManyArgs } from "./AnswerFindManyArgs";
import { AnswerFindUniqueArgs } from "./AnswerFindUniqueArgs";
import { Answer } from "./Answer";
import { PoolQuestion } from "../../poolQuestion/base/PoolQuestion";
import { AnswerService } from "../answer.service";
@graphql.Resolver(() => Answer)
export class AnswerResolverBase {
  constructor(protected readonly service: AnswerService) {}

  async _answersMeta(
    @graphql.Args() args: AnswerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Answer])
  async answers(@graphql.Args() args: AnswerFindManyArgs): Promise<Answer[]> {
    return this.service.findMany(args);
  }

  @Public()
  @graphql.Query(() => Answer, { nullable: true })
  async answer(
    @graphql.Args() args: AnswerFindUniqueArgs
  ): Promise<Answer | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @Public()
  @graphql.Mutation(() => Answer)
  async createAnswer(@graphql.Args() args: CreateAnswerArgs): Promise<Answer> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        poolQuestion: {
          connect: args.data.poolQuestion,
        },
      },
    });
  }

  @graphql.Mutation(() => Answer)
  async updateAnswer(
    @graphql.Args() args: UpdateAnswerArgs
  ): Promise<Answer | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          poolQuestion: {
            connect: args.data.poolQuestion,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Answer)
  async deleteAnswer(
    @graphql.Args() args: DeleteAnswerArgs
  ): Promise<Answer | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @graphql.ResolveField(() => PoolQuestion, {
    nullable: true,
    name: "poolQuestion",
  })
  async resolveFieldPoolQuestion(
    @graphql.Parent() parent: Answer
  ): Promise<PoolQuestion | null> {
    const result = await this.service.getPoolQuestion(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
