/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PoolQuestionService } from "../poolQuestion.service";
import { Public } from "../../decorators/public.decorator";
import { PoolQuestionCreateInput } from "./PoolQuestionCreateInput";
import { PoolQuestionWhereInput } from "./PoolQuestionWhereInput";
import { PoolQuestionWhereUniqueInput } from "./PoolQuestionWhereUniqueInput";
import { PoolQuestionFindManyArgs } from "./PoolQuestionFindManyArgs";
import { PoolQuestionUpdateInput } from "./PoolQuestionUpdateInput";
import { PoolQuestion } from "./PoolQuestion";
import { AnswerFindManyArgs } from "../../answer/base/AnswerFindManyArgs";
import { Answer } from "../../answer/base/Answer";
import { AnswerWhereUniqueInput } from "../../answer/base/AnswerWhereUniqueInput";

export class PoolQuestionControllerBase {
  constructor(protected readonly service: PoolQuestionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PoolQuestion })
  async create(
    @common.Body() data: PoolQuestionCreateInput
  ): Promise<PoolQuestion> {
    return await this.service.create({
      data: {
        ...data,

        pool: data.pool
          ? {
              connect: data.pool,
            }
          : undefined,
      },
      select: {
        answers: true,
        createdAt: true,
        id: true,

        pool: {
          select: {
            id: true,
          },
        },

        question: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [PoolQuestion] })
  @ApiNestedQuery(PoolQuestionFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<PoolQuestion[]> {
    const args = plainToClass(PoolQuestionFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        answers: true,
        createdAt: true,
        id: true,

        pool: {
          select: {
            id: true,
          },
        },

        question: true,
        updatedAt: true,
      },
    });
  }

  @Public()
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PoolQuestion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: PoolQuestionWhereUniqueInput
  ): Promise<PoolQuestion | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        answers: true,
        createdAt: true,
        id: true,

        pool: {
          select: {
            id: true,
          },
        },

        question: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PoolQuestion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: PoolQuestionWhereUniqueInput,
    @common.Body() data: PoolQuestionUpdateInput
  ): Promise<PoolQuestion | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          pool: data.pool
            ? {
                connect: data.pool,
              }
            : undefined,
        },
        select: {
          answers: true,
          createdAt: true,
          id: true,

          pool: {
            select: {
              id: true,
            },
          },

          question: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PoolQuestion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: PoolQuestionWhereUniqueInput
  ): Promise<PoolQuestion | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          answers: true,
          createdAt: true,
          id: true,

          pool: {
            select: {
              id: true,
            },
          },

          question: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/antworten")
  @ApiNestedQuery(AnswerFindManyArgs)
  async findManyAntworten(
    @common.Req() request: Request,
    @common.Param() params: PoolQuestionWhereUniqueInput
  ): Promise<Answer[]> {
    const query = plainToClass(AnswerFindManyArgs, request.query);
    const results = await this.service.findAntworten(params.id, {
      ...query,
      select: {
        answer: true,
        createdAt: true,
        id: true,

        poolQuestion: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/antworten")
  async connectAntworten(
    @common.Param() params: PoolQuestionWhereUniqueInput,
    @common.Body() body: AnswerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      antworten: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/antworten")
  async updateAntworten(
    @common.Param() params: PoolQuestionWhereUniqueInput,
    @common.Body() body: AnswerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      antworten: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/antworten")
  async disconnectAntworten(
    @common.Param() params: PoolQuestionWhereUniqueInput,
    @common.Body() body: AnswerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      antworten: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
