/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PoolService } from "../pool.service";
import { Public } from "../../decorators/public.decorator";
import { PoolCreateInput } from "./PoolCreateInput";
import { PoolWhereInput } from "./PoolWhereInput";
import { PoolWhereUniqueInput } from "./PoolWhereUniqueInput";
import { PoolFindManyArgs } from "./PoolFindManyArgs";
import { PoolUpdateInput } from "./PoolUpdateInput";
import { Pool } from "./Pool";
import { PoolQuestionFindManyArgs } from "../../poolQuestion/base/PoolQuestionFindManyArgs";
import { PoolQuestion } from "../../poolQuestion/base/PoolQuestion";
import { PoolQuestionWhereUniqueInput } from "../../poolQuestion/base/PoolQuestionWhereUniqueInput";

export class PoolControllerBase {
  constructor(protected readonly service: PoolService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Pool })
  async create(@common.Body() data: PoolCreateInput): Promise<Pool> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        currentQuestion: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Pool] })
  @ApiNestedQuery(PoolFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Pool[]> {
    const args = plainToClass(PoolFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        currentQuestion: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @Public()
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Pool })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: PoolWhereUniqueInput
  ): Promise<Pool | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        currentQuestion: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Pool })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: PoolWhereUniqueInput,
    @common.Body() data: PoolUpdateInput
  ): Promise<Pool | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          currentQuestion: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Pool })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: PoolWhereUniqueInput
  ): Promise<Pool | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          currentQuestion: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/poolQuestions")
  @ApiNestedQuery(PoolQuestionFindManyArgs)
  async findManyPoolQuestions(
    @common.Req() request: Request,
    @common.Param() params: PoolWhereUniqueInput
  ): Promise<PoolQuestion[]> {
    const query = plainToClass(PoolQuestionFindManyArgs, request.query);
    const results = await this.service.findPoolQuestions(params.id, {
      ...query,
      select: {
        answers: true,
        createdAt: true,
        id: true,

        pool: {
          select: {
            id: true,
          },
        },

        question: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/poolQuestions")
  async connectPoolQuestions(
    @common.Param() params: PoolWhereUniqueInput,
    @common.Body() body: PoolQuestionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      poolQuestions: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/poolQuestions")
  async updatePoolQuestions(
    @common.Param() params: PoolWhereUniqueInput,
    @common.Body() body: PoolQuestionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      poolQuestions: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/poolQuestions")
  async disconnectPoolQuestions(
    @common.Param() params: PoolWhereUniqueInput,
    @common.Body() body: PoolQuestionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      poolQuestions: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
